name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f docker-compose-build.yml build
        
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: index.docker.io
          username: ${{ secrets.DOCKERHUB_PASS }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Push the stack
        run: docker-compose -f docker-compose-build.yml push      
